name: CI

on: [push, pull_request]

jobs:

  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        otp: ['20', '25', '26', '27', '28']
    runs-on: ubuntu-24.04
    container:
      image: public.ecr.aws/docker/library/erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v2
    - run: ./configure
    - run: make
    - run: rebar3 compile
    - run: rebar3 xref
    - run: rebar3 dialyzer
    - run: rebar3 eunit -v

  cover:
    name: Cover
    needs: [tests]
    runs-on: ubuntu-24.04
    container:
      image: public.ecr.aws/docker/library/erlang
    steps:
    - uses: actions/checkout@v2
    - name: Prepare libraries
      run: |
        apt-get -qq update
        apt-get -qq install libyaml-dev
    - run: ./configure --enable-gcov
    - run: rebar3 compile
    - name: Run tests to obtain Erlang coverage
      run: |
        mv test/unload_test.erl .
        rebar3 eunit -v
        mv _build/test/cover/eunit.coverdata .
    - name: Run tests to obtain C coverage
      run: |
        mv unload_test.erl test/
        rebar3 eunit -v
        mv eunit.coverdata _build/test/cover/
    - name: Send to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get -qq install pipx
        pipx install cpp-coveralls
        /github/home/.local/bin/cpp-coveralls -b `pwd` --verbose --gcov-options '\-lp' --dump c.json
        ADDJSONFILE=c.json COVERALLS=true rebar3 as test coveralls send
        curl -v -k https://coveralls.io/webhook \
             --header "Content-Type: application/json" \
             --data '{"repo_name":"$GITHUB_REPOSITORY",
                      "repo_token":"$GITHUB_TOKEN",
                      "payload":{"build_num":$GITHUB_RUN_ID,
                                 "status":"done"}}'
